-- Base app schema
-- User
CREATE TABLE "users" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (
    START
    WITH
      1000
  ) PRIMARY KEY,
  username varchar(128) NOT NULL UNIQUE
)
-- Task
CREATE TABLE "tasks" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (
    START
    WITH
      1000
  ) PRIMARY KEY,
  title varchar(256) NOT NULL
)
